name: sharebites
description: "A Food Donation Matcher App with C++ Backend."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.3
  firebase_database: ^11.2.1
  firebase_messaging: ^15.1.5

  # Push Notifications
  onesignal_flutter: ^5.2.9

  # Backend Services
  supabase_flutter: ^2.9.1

  # Google Services
  google_maps_flutter: ^2.10.0
  google_sign_in: ^6.2.2

  # ML Kit
  google_mlkit_text_recognition: ^0.15.1

  # State Management
  provider: ^6.1.2

  # HTTP & Networking
  http: ^1.2.2
  dio: ^5.7.0

  # Image Handling
  image_picker: ^1.1.2

  # Utilities
  intl: ^0.20.1
  url_launcher: ^6.3.1
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Add assets if you have any
  # assets:
  #   - images/
  #   - assets/